services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
    links:
    - db
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    restart: always
  db:
    environment:
      POSTGRES_DB: sumup
      POSTGRES_PASSWORD: sumup
      POSTGRES_USER: sumup
    image: postgres:14.1-alpine
    networks:
      default: null
    ports:
    - mode: ingress
      target: 5432
      published: "5432"
      protocol: tcp
    restart: always
networks:
  default:
    name: sumup_default
